from copy import deepcopy
from typing import Any, Optional


RULE_POLICY_VERSION = "2026-06-19"


def _rule(
    rule_id: str,
    predicate: str,
    relation_family: str,
    subject_type: str,
    object_type: str,
    trigger_condition: str,
    required_evidence: str,
    evidence_source_tables: list[str],
    confidence_logic: str,
    default_status: str,
    extraction_method: str,
    visible_by_default: bool,
    candidate_only: bool,
    *details: str,
    implemented: bool = True,
) -> dict[str, Any]:
    if len(details) == 6:
        (
            methodological_note,
            limitation_caution,
            meaning,
            does_not_mean,
            accepted_when,
            needs_review_when,
        ) = details
    elif len(details) == 4:
        meaning, does_not_mean, accepted_when, needs_review_when = details
        methodological_note = meaning
        limitation_caution = does_not_mean
    else:
        raise ValueError(f"Relation rule {rule_id} must provide four or six methodological detail fields")
    return {
        "rule_id": rule_id,
        "predicate": predicate,
        "relation_family": relation_family,
        "subject_type": subject_type,
        "object_type": object_type,
        "trigger_condition": trigger_condition,
        "required_evidence": required_evidence,
        "evidence_source_tables": evidence_source_tables,
        "confidence_logic": confidence_logic,
        "default_status": default_status,
        "extraction_method": extraction_method,
        "visible_by_default": visible_by_default,
        "candidate_only": candidate_only,
        "methodological_note": methodological_note,
        "limitation_caution": limitation_caution,
        "meaning": meaning,
        "does_not_mean": does_not_mean,
        "accepted_when": accepted_when,
        "needs_review_when": needs_review_when,
        "implemented": implemented,
    }


RELATION_RULES: dict[str, dict[str, Any]] = {
    "structural.collection.metadata": _rule(
        "structural.collection.metadata",
        "belongs_to_collection",
        "structural",
        "material",
        "collection",
        "A material has a non-empty collection metadata value.",
        "One material metadata record containing the collection value.",
        ["materials", "kg_mentions", "kg_relation_evidence"],
        "Fixed at 1.0 for the stored metadata assertion.",
        "accepted",
        "metadata",
        True,
        False,
        "This is a direct projection of repository metadata, not an inferred grouping.",
        "A collection value may reflect local cataloguing practice and does not prove historical ownership, provenance, or archival custody.",
        "the repository record is catalogued in the named collection",
        "the material was necessarily created, owned, or physically held by that collection",
        "The metadata field is present and has not been manually rejected.",
        "Review when the collection field is imported, ambiguous, or known to combine unlike cataloguing systems.",
    ),
    "structural.source_type.metadata": _rule(
        "structural.source_type.metadata",
        "has_source_type",
        "structural",
        "material",
        "source_type",
        "A material has a non-empty source_type metadata value.",
        "One material metadata record containing the source type.",
        ["materials", "kg_mentions", "kg_relation_evidence"],
        "Fixed at 1.0 for the stored metadata assertion.",
        "accepted",
        "metadata",
        True,
        False,
        "This edge exposes the repository's current source classification.",
        "Source type is a cataloguing category and does not by itself establish genre, reliability, authorship, or evidential quality.",
        "the repository currently classifies the material as the named source type",
        "the material satisfies every scholarly definition associated with that type",
        "The metadata field is present and has not been manually rejected.",
        "Review when a source could reasonably belong to multiple types or the value was automatically imported.",
    ),
    "bibliographic.author.metadata": _rule(
        "bibliographic.author.metadata",
        "authored_by",
        "bibliographic",
        "material",
        "agent",
        "The authors metadata field is split into one or more named agents.",
        "One material metadata record containing the author string.",
        ["materials", "kg_mentions", "kg_relation_evidence"],
        "Fixed at 0.99 because string splitting does not perform authority control.",
        "accepted",
        "metadata",
        True,
        False,
        "Author names are normalized as labels but are not reconciled against an external authority file.",
        "Matching name strings do not prove that two records refer to the same person, and authorship does not imply endorsement of every claim in a source.",
        "the repository metadata attributes the material to the named agent",
        "the agent identity has been externally disambiguated or every statement in the material is the agent's own position",
        "The author metadata is explicit and has not been manually rejected.",
        "Review when names are abbreviated, collective, translated, duplicated, or otherwise ambiguous.",
    ),
    "semantic.topic.manual_keyword": _rule(
        "semantic.topic.manual_keyword",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "A human-edited keyword is stored on the material.",
        "One accepted keyword mention tied to the material metadata.",
        ["materials", "kg_mentions", "kg_relation_evidence"],
        "The accepted keyword mention contributes confidence 0.98; aggregated relations use the arithmetic mean of evidence confidences.",
        "accepted",
        "keyword",
        True,
        False,
        "The edge means the concept is an assigned topic of the repository material.",
        "A topic assignment does not prove that the material supports, rejects, or centrally discusses a proposition involving the concept.",
        "At least one non-rejected human-edited keyword mention supports the material-concept pair.",
        "Review when the keyword was bulk imported, is overly broad, or does not match the material.",
    ),
    "semantic.topic.auto_keyword": _rule(
        "semantic.topic.auto_keyword",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "An automatically generated keyword is stored on the material.",
        "One auto_keyword mention tied to material metadata.",
        ["materials", "kg_mentions", "kg_relation_evidence"],
        "Each automatic keyword mention contributes confidence 0.72; aggregated relations use the arithmetic mean.",
        "needs_review",
        "auto_keyword",
        True,
        False,
        "Automatic keywords are retained as reviewable topic assertions so they remain inspectable.",
        "An automatic keyword is not a verified subject heading and must not be treated as a human interpretation.",
        "A reviewer explicitly accepts the relation, or independent accepted evidence supports the same material-concept pair.",
        "By default, and whenever the generated keyword is vague, context-free, or unsupported by source evidence.",
    ),
    "semantic.topic.exact_match": _rule(
        "semantic.topic.exact_match",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "A previously accepted concept label appears as a whole normalized phrase in extracted text.",
        "One extracted segment containing the accepted concept label.",
        ["extracted_segments", "kg_mentions", "kg_relation_evidence"],
        "Each exact text match contributes confidence 0.82; aggregated relations use the arithmetic mean.",
        "accepted",
        "exact_match",
        True,
        False,
        "Exact matching reuses a concept vocabulary grounded in manual keywords or human observations.",
        "Textual presence does not establish the sense, stance, referent, importance, or truth of the matched concept.",
        "The vocabulary label is already accepted and the exact match has not been rejected.",
        "Review homonyms, quoted text, OCR errors, negation, and cases where the same phrase has multiple senses.",
    ),
    "semantic.topic.image_ocr": _rule(
        "semantic.topic.image_ocr",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "A previously accepted concept label appears in OCR text extracted from an image.",
        "One image_evidence OCR record containing the accepted concept label.",
        ["image_evidence", "kg_mentions", "kg_relation_evidence"],
        "Each image OCR match contributes confidence 0.76; aggregated relations use the arithmetic mean.",
        "accepted",
        "image_ocr",
        True,
        False,
        "The relation preserves the image evidence locator so OCR can be checked against the source image.",
        "OCR is error-prone and textual presence in an image does not prove the depicted object or intended meaning.",
        "The concept vocabulary is accepted and the OCR match has not been rejected.",
        "Review low-quality scans, non-Latin scripts, tables, captions, and likely OCR substitutions.",
    ),
    "semantic.topic.image_caption": _rule(
        "semantic.topic.image_caption",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "A previously accepted concept label appears in stored image caption text.",
        "One image_evidence caption record containing the accepted concept label.",
        ["image_evidence", "kg_mentions", "kg_relation_evidence"],
        "Each caption match contributes confidence 0.76; aggregated relations use the arithmetic mean.",
        "accepted",
        "image_caption",
        True,
        False,
        "Caption text is treated as source-linked textual evidence rather than visual recognition.",
        "A caption match does not independently verify what is visible in the image or who supplied the caption.",
        "The concept vocabulary is accepted and the caption match has not been rejected.",
        "Review generated captions, translated captions, ambiguous captions, and captions detached from their image context.",
    ),
    "semantic.topic.aggregated": _rule(
        "semantic.topic.aggregated",
        "has_topic",
        "semantic",
        "material",
        "concept",
        "Two or more topic evidence methods support the same material-concept pair.",
        "One or more kg_relation_evidence rows derived from topic mentions.",
        ["kg_mentions", "kg_relation_evidence"],
        "Arithmetic mean of contributing evidence confidences; evidence_count is unique evidence units and document_count is distinct materials.",
        "accepted_if_any_accepted_evidence",
        "aggregated_evidence",
        True,
        False,
        "The explanation endpoint lists the contributing rule IDs and methods when the graph has been rebuilt with provenance.",
        "Aggregation does not make weak evidence independent; several mentions may derive from the same document or repeated text.",
        "At least one contributing evidence path is accepted, or a reviewer explicitly accepts the relation.",
        "All contributing evidence paths are review-only, or the accepted path is later rejected.",
    ),
    "semantic.observation_topic.human": _rule(
        "semantic.observation_topic.human",
        "has_observation_topic",
        "semantic",
        "material",
        "concept",
        "A human observation records a concept against a material.",
        "One observations row with its source locator or contextual note.",
        ["observations", "kg_mentions", "kg_relation_evidence"],
        "Each human observation contributes confidence 0.99.",
        "accepted",
        "human_observation",
        True,
        False,
        "This is an assertion made by a repository researcher and remains traceable to the observation record.",
        "The observation is not automatically a fact about the world, a consensus interpretation, or a statement made by the source author.",
        "The observation is intentionally recorded by a human and has not been rejected.",
        "Review when the observation lacks a source locator, conflates description with interpretation, or requires domain adjudication.",
    ),
    "spatial.place.metadata": _rule(
        "spatial.place.metadata",
        "mentions_place",
        "spatial",
        "material",
        "place",
        "The material has a non-empty region metadata value.",
        "One material metadata record containing the region label.",
        ["materials", "kg_place_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Fixed at 0.95 for trusted repository region metadata.",
        "accepted",
        "metadata",
        True,
        False,
        "Region metadata creates a resolved place entity even when coordinates are not supplied.",
        "A region field may describe coverage, publication context, provenance, or another cataloguing choice; it does not necessarily identify an event location.",
        "The region metadata is explicit and has not been rejected.",
        "Review when the region field mixes multiple places, uses historical names, or lacks a clear spatial role.",
    ),
    "spatial.place.human_observation": _rule(
        "spatial.place.human_observation",
        "mentions_place",
        "spatial",
        "material",
        "place",
        "A human observation with observation_type=place names a place.",
        "One place observation with source context.",
        ["observations", "kg_place_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Fixed at 0.99 for the human-entered place assertion.",
        "accepted",
        "human_observation",
        True,
        False,
        "The observation resolves the label locally but does not perform external gazetteer disambiguation.",
        "A human-entered place name does not guarantee a unique geographic referent or coordinates.",
        "The place observation is explicit and has not been rejected.",
        "Review homonymous places, historical boundaries, translated names, and observations without source context.",
    ),
    "spatial.place.pattern": _rule(
        "spatial.place.pattern",
        "mentions_place",
        "spatial",
        "material",
        "place",
        "A capitalized phrase follows a spatial cue and is resolved by explicit coordinates or a saved resolution decision.",
        "Pattern evidence plus either valid explicit coordinates or an accepted place-resolution override.",
        ["extracted_segments", "image_evidence", "kg_place_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Segment candidates contribute 0.65-0.72; image candidates contribute 0.65. Aggregated relations use the arithmetic mean.",
        "needs_review",
        "pattern_extraction",
        True,
        False,
        "Unresolved labels remain in kg_place_resolution and do not create semantic place relations.",
        "Capitalization and spatial prepositions are weak signals; organizations, people, headings, and OCR fragments may be misidentified as places.",
        "A reviewer resolves the place label, or a reviewer accepts the resulting relation.",
        "By default for pattern-derived places, including explicit-coordinate matches until the referent and role are checked.",
    ),
    "spatial.place.aggregated": _rule(
        "spatial.place.aggregated",
        "mentions_place",
        "spatial",
        "material",
        "place",
        "Multiple spatial evidence methods support the same material-place pair.",
        "One or more relation evidence rows from resolved place mentions.",
        ["kg_mentions", "kg_place_resolution", "kg_relation_evidence"],
        "Arithmetic mean of contributing mention confidences.",
        "accepted_if_any_accepted_evidence",
        "aggregated_evidence",
        True,
        False,
        "Accepted metadata or human evidence may coexist with review-only pattern evidence.",
        "Aggregating mentions does not determine whether the place is a subject, origin, event location, publication place, or comparison.",
        "At least one contributing evidence path is accepted, or a reviewer explicitly accepts the relation.",
        "All contributing paths are pattern-derived or otherwise need review.",
    ),
    "temporal.time.metadata": _rule(
        "temporal.time.metadata",
        "mentions_time",
        "temporal",
        "material",
        "time_period",
        "The material year metadata parses as a valid publication year or year range.",
        "One material metadata record with a resolved year expression.",
        ["materials", "kg_time_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Fixed at 0.98 for resolved publication/material year metadata.",
        "accepted",
        "metadata",
        True,
        False,
        "The edge normally represents the material's publication or catalogued year.",
        "The metadata year does not necessarily date every event, object, quotation, or claim discussed in the material.",
        "The year parses as a valid temporal expression and has not been rejected.",
        "Review uncertain dates, ranges with unclear semantics, and records where publication and collection dates are conflated.",
    ),
    "temporal.time.human_observation": _rule(
        "temporal.time.human_observation",
        "mentions_time",
        "temporal",
        "material",
        "time_period",
        "A temporal expression in a human observation passes temporal resolution checks.",
        "One observation with a resolved temporal expression and source context.",
        ["observations", "kg_time_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Uses the temporal parser confidence, normally 0.80-0.90 for explicit years, eras, or BP expressions.",
        "accepted",
        "human_observation",
        True,
        False,
        "Human observation context makes the temporal assertion attributable and reviewable.",
        "The date may describe a source passage rather than the material as a whole, and parser resolution does not establish the event type.",
        "The expression is resolved and the human observation has not been rejected.",
        "Review ambiguous calendars, relative dates, date ranges without event context, and observations lacking a locator.",
    ),
    "temporal.time.pattern": _rule(
        "temporal.time.pattern",
        "mentions_time",
        "temporal",
        "material",
        "time_period",
        "A year, era, BP expression, or plausible range is extracted from segment/image text and passes validity checks.",
        "One resolved temporal candidate that is not identified as a page, figure, table, plate, or invalid numeric reference.",
        ["extracted_segments", "image_evidence", "kg_time_resolution", "kg_resolution_evidence", "kg_relation_evidence"],
        "Parser confidence ranges from 0.55 to 0.90 according to explicit temporal syntax and context.",
        "needs_review",
        "pattern_extraction",
        True,
        False,
        "Invalid page/reference ranges remain in kg_time_resolution and do not create time entities or relations.",
        "A valid-looking number may still be a measurement, identifier, cited page, accession number, or date with an unclear role.",
        "A reviewer accepts the relation or an accepted metadata/human evidence path supports the same material-time pair.",
        "By default for segment and image pattern extraction.",
    ),
    "temporal.time.aggregated": _rule(
        "temporal.time.aggregated",
        "mentions_time",
        "temporal",
        "material",
        "time_period",
        "Multiple temporal evidence methods support the same material-time pair.",
        "One or more relation evidence rows from resolved time mentions.",
        ["kg_mentions", "kg_time_resolution", "kg_relation_evidence"],
        "Arithmetic mean of contributing mention confidences.",
        "accepted_if_any_accepted_evidence",
        "aggregated_evidence",
        True,
        False,
        "Accepted metadata/human evidence can coexist with review-only pattern evidence.",
        "Repeated dates in one source do not establish independent corroboration or the date's interpretive role.",
        "At least one contributing evidence path is accepted, or a reviewer explicitly accepts the relation.",
        "All contributing paths are pattern-derived or otherwise need review.",
    ),
    "candidate.cooccurrence": _rule(
        "candidate.cooccurrence",
        "co_occurs_with",
        "semantic",
        "concept",
        "concept",
        "Two non-generic concepts co-occur in at least three unique evidence units across at least two documents and pass coverage filters.",
        "At least three candidate evidence units from at least two distinct materials.",
        ["kg_mentions", "kg_entity_stats", "kg_candidate_relations", "kg_candidate_evidence"],
        "min(0.90, 0.45 + 0.04 × evidence_count + 0.08 × document_count); candidates below 0.55 are discarded.",
        "needs_review",
        "cooccurrence",
        False,
        True,
        "Co-occurrence is stored outside kg_relations and does not appear in the default Semantic Atlas.",
        "Co-occurrence does not establish semantic similarity, causation, identity, hierarchy, influence, or any directional relation.",
        "A reviewer explicitly accepts the candidate, which promotes it to a related_to relation.",
        "Always, until a researcher reviews the evidence units and specifies that a generic relatedness assertion is defensible.",
    ),
    "candidate.embedding_neighbor": _rule(
        "candidate.embedding_neighbor",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "Reserved for a future embedding-neighbor candidate generator; no generator currently writes these candidates.",
        "Would require stored vector-neighbor evidence and model/version provenance.",
        ["kg_candidate_relations", "kg_candidate_evidence"],
        "Not implemented.",
        "needs_review",
        "embedding_neighbor",
        False,
        True,
        "The schema permits this method, but the current semantic graph builder does not generate it.",
        "Embedding proximity is model-dependent and does not establish a scholarly relation without review.",
        "Only after explicit human review of source evidence and model provenance.",
        "Always if introduced.",
        implemented=False,
    ),
    "candidate.pattern_extraction": _rule(
        "candidate.pattern_extraction",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "Reserved for future relation-pattern candidates; no generator currently writes these candidates.",
        "Would require a source-linked linguistic pattern and candidate evidence rows.",
        ["kg_candidate_relations", "kg_candidate_evidence"],
        "Not implemented.",
        "needs_review",
        "pattern_extraction",
        False,
        True,
        "Pattern-derived relation candidates must remain outside accepted relations until reviewed.",
        "A textual pattern alone may not encode the intended relation and may be affected by negation or quotation.",
        "Only after explicit human review.",
        "Always if introduced.",
        implemented=False,
    ),
    "candidate.llm": _rule(
        "candidate.llm",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "Reserved for future LLM-proposed candidates; no generator currently writes these candidates.",
        "Would require prompt/model/version provenance plus source-linked candidate evidence.",
        ["kg_candidate_relations", "kg_candidate_evidence"],
        "Not implemented.",
        "needs_review",
        "llm_candidate",
        False,
        True,
        "LLM output may suggest a candidate but cannot directly create an accepted semantic assertion.",
        "A fluent model explanation is not empirical evidence and may introduce unsupported relations.",
        "Only after explicit human review against repository evidence.",
        "Always if introduced.",
        implemented=False,
    ),
    "semantic.related_to.reviewed_cooccurrence": _rule(
        "semantic.related_to.reviewed_cooccurrence",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "A researcher explicitly accepts a co_occurs_with candidate.",
        "Accepted kg_candidate_relations row plus its kg_candidate_evidence rows.",
        ["kg_candidate_relations", "kg_candidate_evidence", "kg_review_decisions", "kg_relation_evidence"],
        "Carries forward the reviewed candidate confidence.",
        "accepted",
        "reviewed_cooccurrence",
        True,
        False,
        "Promotion changes the predicate from co_occurs_with to the intentionally broad related_to.",
        "Even after review, related_to does not specify identity, hierarchy, causation, influence, or direction.",
        "The candidate has an explicit accepted review decision.",
        "Never accepted automatically from co-occurrence alone.",
    ),
    "semantic.related_to.reviewed_embedding": _rule(
        "semantic.related_to.reviewed_embedding",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "A researcher explicitly accepts an embedding-neighbor candidate.",
        "Accepted embedding candidate evidence and model provenance.",
        ["kg_candidate_relations", "kg_candidate_evidence", "kg_review_decisions", "kg_relation_evidence"],
        "Carries forward the reviewed candidate confidence.",
        "accepted",
        "reviewed_embedding_neighbor",
        True,
        False,
        "The promotion path is supported, but no embedding candidates are currently generated.",
        "The accepted edge remains model- and corpus-dependent and should not be read as an objective semantic fact.",
        "The candidate has an explicit accepted review decision.",
        "Never accepted automatically from vector proximity.",
        implemented=False,
    ),
    "semantic.related_to.reviewed_pattern": _rule(
        "semantic.related_to.reviewed_pattern",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "A researcher explicitly accepts a relation-pattern candidate.",
        "Accepted pattern candidate and source-linked evidence.",
        ["kg_candidate_relations", "kg_candidate_evidence", "kg_review_decisions", "kg_relation_evidence"],
        "Carries forward the reviewed candidate confidence.",
        "accepted",
        "reviewed_pattern_extraction",
        True,
        False,
        "The promotion path is supported, but no relation-pattern candidates are currently generated.",
        "Pattern matching may miss negation, modality, quotation, and relation direction.",
        "The candidate has an explicit accepted review decision.",
        "Never accepted automatically from a pattern.",
        implemented=False,
    ),
    "semantic.related_to.reviewed_llm": _rule(
        "semantic.related_to.reviewed_llm",
        "related_to",
        "semantic",
        "concept",
        "concept",
        "A researcher explicitly accepts an LLM-proposed candidate.",
        "Accepted LLM candidate with prompt/model/version provenance and source-linked evidence.",
        ["kg_candidate_relations", "kg_candidate_evidence", "kg_review_decisions", "kg_relation_evidence"],
        "Carries forward the reviewed candidate confidence.",
        "accepted",
        "reviewed_llm_candidate",
        True,
        False,
        "The promotion path is supported, but no LLM candidates are currently generated.",
        "Human acceptance must be based on repository evidence, not on model fluency.",
        "The candidate has an explicit accepted review decision.",
        "Never accepted automatically from LLM output.",
        implemented=False,
    ),
    "reserved.same_as": _rule(
        "reserved.same_as",
        "same_as",
        "semantic",
        "any",
        "any",
        "No current builder rule.",
        "Would require authority control or explicit human identity review.",
        [],
        "Not implemented.",
        "needs_review",
        "not_implemented",
        False,
        True,
        "Listed to make the absence of identity edges explicit.",
        "String equality, label normalization, or embedding similarity is not sufficient for identity.",
        "Only after explicit authority-based or human identity review.",
        "Always if introduced.",
        implemented=False,
    ),
    "reserved.broader_than": _rule(
        "reserved.broader_than",
        "broader_than",
        "semantic",
        "concept",
        "concept",
        "No current builder rule.",
        "Would require an explicit curated hierarchy or reviewed source assertion.",
        [],
        "Not implemented.",
        "needs_review",
        "not_implemented",
        False,
        True,
        "Listed to prevent co-occurrence or similarity from being mistaken for hierarchy.",
        "Frequency, co-occurrence, or embedding distance does not establish a broader concept.",
        "Only after explicit hierarchy review.",
        "Always if introduced.",
        implemented=False,
    ),
    "reserved.narrower_than": _rule(
        "reserved.narrower_than",
        "narrower_than",
        "semantic",
        "concept",
        "concept",
        "No current builder rule.",
        "Would require an explicit curated hierarchy or reviewed source assertion.",
        [],
        "Not implemented.",
        "needs_review",
        "not_implemented",
        False,
        True,
        "Listed to prevent co-occurrence or similarity from being mistaken for hierarchy.",
        "Frequency, co-occurrence, or embedding distance does not establish a narrower concept.",
        "Only after explicit hierarchy review.",
        "Always if introduced.",
        implemented=False,
    ),
    "reserved.near_in_evidence": _rule(
        "reserved.near_in_evidence",
        "near_in_evidence",
        "semantic",
        "concept",
        "concept",
        "No current builder rule; evidence-unit co-occurrence is represented only by hidden co_occurs_with candidates.",
        "Would require a defined window, unit type, ordering rule, and source-linked evidence.",
        ["kg_candidate_relations", "kg_candidate_evidence"],
        "Not implemented.",
        "needs_review",
        "not_implemented",
        False,
        True,
        "The rule is explicitly hidden until proximity semantics are implemented and tested.",
        "Document-level or evidence-unit co-occurrence must not be described as textual proximity without a defined window.",
        "Only after implementation and explicit review.",
        "Always if introduced.",
        implemented=False,
    ),
}


RELATION_METHOD_RULE_IDS: dict[tuple[str, str], str] = {
    ("belongs_to_collection", "metadata"): "structural.collection.metadata",
    ("has_source_type", "metadata"): "structural.source_type.metadata",
    ("authored_by", "metadata"): "bibliographic.author.metadata",
    ("has_topic", "keyword"): "semantic.topic.manual_keyword",
    ("has_topic", "auto_keyword"): "semantic.topic.auto_keyword",
    ("has_topic", "exact_match"): "semantic.topic.exact_match",
    ("has_topic", "image_ocr"): "semantic.topic.image_ocr",
    ("has_topic", "image_caption"): "semantic.topic.image_caption",
    ("has_topic", "aggregated_evidence"): "semantic.topic.aggregated",
    ("has_observation_topic", "human_observation"): "semantic.observation_topic.human",
    ("mentions_place", "metadata"): "spatial.place.metadata",
    ("mentions_place", "human_observation"): "spatial.place.human_observation",
    ("mentions_place", "pattern_extraction"): "spatial.place.pattern",
    ("mentions_place", "aggregated_evidence"): "spatial.place.aggregated",
    ("mentions_time", "metadata"): "temporal.time.metadata",
    ("mentions_time", "human_observation"): "temporal.time.human_observation",
    ("mentions_time", "pattern_extraction"): "temporal.time.pattern",
    ("mentions_time", "aggregated_evidence"): "temporal.time.aggregated",
    ("related_to", "reviewed_cooccurrence"): "semantic.related_to.reviewed_cooccurrence",
    ("related_to", "reviewed_embedding_neighbor"): "semantic.related_to.reviewed_embedding",
    ("related_to", "reviewed_pattern_extraction"): "semantic.related_to.reviewed_pattern",
    ("related_to", "reviewed_llm_candidate"): "semantic.related_to.reviewed_llm",
}

CANDIDATE_METHOD_RULE_IDS: dict[tuple[str, str], str] = {
    ("co_occurs_with", "cooccurrence"): "candidate.cooccurrence",
    ("related_to", "embedding_neighbor"): "candidate.embedding_neighbor",
    ("related_to", "pattern_extraction"): "candidate.pattern_extraction",
    ("related_to", "llm_candidate"): "candidate.llm",
}

AGGREGATE_RULE_IDS = {
    "has_topic": "semantic.topic.aggregated",
    "mentions_place": "spatial.place.aggregated",
    "mentions_time": "temporal.time.aggregated",
}


def relation_rule_ids(
    predicate: str,
    extraction_method: str,
    properties: Optional[dict[str, Any]] = None,
) -> list[str]:
    stored = (properties or {}).get("rule_ids")
    if isinstance(stored, list):
        valid = [rule_id for rule_id in stored if rule_id in RELATION_RULES]
        if valid:
            return sorted(set(valid))
    direct = RELATION_METHOD_RULE_IDS.get((predicate, extraction_method))
    if direct:
        return [direct]
    aggregate = AGGREGATE_RULE_IDS.get(predicate)
    if extraction_method == "aggregated_evidence" and aggregate:
        return [aggregate]
    implemented = [
        rule_id
        for rule_id, rule in RELATION_RULES.items()
        if rule["predicate"] == predicate and rule["implemented"] and not rule["candidate_only"]
    ]
    return sorted(implemented[:1])


def primary_relation_rule_id(
    predicate: str,
    extraction_method: str,
    properties: Optional[dict[str, Any]] = None,
) -> str:
    if extraction_method == "aggregated_evidence" and predicate in AGGREGATE_RULE_IDS:
        return AGGREGATE_RULE_IDS[predicate]
    rule_ids = relation_rule_ids(predicate, extraction_method, properties)
    if rule_ids:
        return rule_ids[0]
    return f"unregistered:{predicate}:{extraction_method}"


def candidate_rule_id(predicate: str, candidate_method: str) -> Optional[str]:
    return CANDIDATE_METHOD_RULE_IDS.get((predicate, candidate_method))


def semantic_relation_rules_payload() -> dict[str, Any]:
    rules = [deepcopy(RELATION_RULES[rule_id]) for rule_id in sorted(RELATION_RULES)]
    return {
        "policy_version": RULE_POLICY_VERSION,
        "rules": rules,
        "count": len(rules),
        "policy": {
            "accepted_by_default": (
                "Direct repository metadata, accepted manual keywords/exact matches, and explicit human observations "
                "may be accepted when their rule states that policy."
            ),
            "review_by_default": (
                "Pattern, co-occurrence, embedding, and LLM-derived assertions default to needs_review and cannot "
                "become accepted semantic relations without accepted evidence or an explicit review decision."
            ),
            "counts": (
                "evidence_count counts unique source-linked evidence units; document_count counts distinct material_id "
                "values represented by those evidence units."
            ),
        },
    }
